// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXtcTNFjbPLDfSTDNjkGrZx2GLL2qtee8',
    appId: '1:655715951200:web:d1cdf17ff48fa1f9275905',
    messagingSenderId: '655715951200',
    projectId: 'users-authentication-84704',
    authDomain: 'users-authentication-84704.firebaseapp.com',
    storageBucket: 'users-authentication-84704.appspot.com',
    measurementId: 'G-RERDRE518X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHuDE0GLXcgvlhgXc4cmC_nnBXtOGi_l4',
    appId: '1:655715951200:android:1e3ce462f5433dd5275905',
    messagingSenderId: '655715951200',
    projectId: 'users-authentication-84704',
    storageBucket: 'users-authentication-84704.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApGqBV0mVoNppmjr92OT0eGymS7FS5RsY',
    appId: '1:655715951200:ios:5642ebad392b75c8275905',
    messagingSenderId: '655715951200',
    projectId: 'users-authentication-84704',
    storageBucket: 'users-authentication-84704.appspot.com',
    iosClientId: '655715951200-ghfj37sqmb085eeck0v6nghs4gdi995n.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalHackathon',
  );
}
